### ISSUE TITLE
User page

### ISSUE THREAD

**Issue by jankapunkt** [leaonline/leaonline-teacher#32]
We need to display the current course on the course page with all i's containing data.

### Preliminaries

- [x] Please create a new branch: `ui-course-page`
- [ ] Open a **draft** pull request - once complete set from draft to PR
- [x] update Meteor to 2.0 (use `update_packages.sh` and `commit_update.sh`)
- [x] update AutoForm to `aldeed:autoform@7.0.0!`
- [x] use `communitypackages:autoform-bootstrap4` instead of `jkuester:autoform-bootstrap4`
- [ ] if there are scss errors after update, please open an issue!

### Todos:

- [ ] Implement XYZ... (edit these on your own)

### Resources:

Screens: https://xd.adobe.com/view/150822d9-2fd7-4e79-ab83-f97c4508e8f9-405b/
Link updated 11.2.2020 

Schemas:

*competency categories*

```javascript
{
  _id: String,
  title: String
}
```

*competency*

Describes a competency, independently from user status

```javascript
{
  _id: String,
  title: String,
  competencyCategory: String, // this is the _id of one of the above
  description: String, // the text in grey
  help: String, // should appear when clicking on the i symbol,
  alphaLevel: Number, // one of 1 - 5
}
```

*user competency status*

Describes a user's achievement of a competency

``` javascript
{
  _id: String,
  userId: String, // the _id of the associated user
  competency: String, // _id of the associated competency
  fulfilled: Number, // 0 to 1,
  testId: String, // _id of a test
  developmentStatus: Number, // 0 - 3, map with Development -> index
}
```

*DevelopmentStatus* 

```javascript
export const DevelopmentStatus = {
  firstTime: { index: 0, name: 'firstTime', label: 'developmentStatus.firstTime' },
  // ...
}
```

*AlphaLevels* 

```javascript
export const AlphaLevels = {
  one: { index: 1, name: 'one', label: '1' },
  // ...
}
```

### Contraints

- please always ensure linters are passing locally before pushing!
- please do many commits for small steps (not few commits for many files)
- keep the UI as close as defined by the screens
- use [Bootstrap classes](https://getbootstrap.com/docs/4.6/getting-started/introduction/) always in favour of direct (s)css manipulation!
- use translation labels for any application-wide (static) labels (headlines, buttons, descriptions; but not for labels, defined by data from the database)
